### ISSUE TITLE
FodyWeaver not working as expected

### ISSUE THREAD

**Issue by tomShoutTheSecond** [tomShoutTheSecond/SiaTesting#11]
Although FodyWeaver appears to be included in the project (it was automatically added when installing the Realm nuget), RaisePropertyChanged() is not being invoked automatically when changing the state of, for example, a simple bool property, so we have to call RaisePropertyChanged() on every property, every time it changes

See also: https://github.com/tomShoutTheSecond/SiaTesting/issues/4

**Comment by jacobh-gh** [comment]
I think we could close this.

**Comment by tomShoutTheSecond** [comment]
Yes
